services:
  web:
    build: .
    expose:
      - "3000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grabpflege-albrecht.rule=Host(`grabpflege-albrecht.de`) || Host(`www.grabpflege-albrecht.de`)"
      - "traefik.http.routers.grabpflege-albrecht.entrypoints=websecure"
      - "traefik.http.routers.grabpflege-albrecht.tls.certresolver=letsencrypt"
      - "traefik.http.services.grabpflege-albrecht.loadbalancer.server.port=3000"
